In [2]:
import torch
import torchvision

In [5]:
#one dimensional tensor
a = torch.tensor([2,2,1])
print(a)

tensor([2, 2, 1])


In [14]:
#two dimensional tensor
b = torch.tensor([[2,2,1],[1,1,1],[3,4,5]])
print(b)

tensor([[2, 2, 1],
        [1, 1, 1],
        [3, 4, 5]])


In [15]:
#the size of the tensors
print(a.shape)
print(b.shape)
print(a.size())
print(b.size())

torch.Size([3])
torch.Size([3, 3])
torch.Size([3])
torch.Size([3, 3])


In [16]:
#get the hight oor number of rows of b
print(b.shape[0])

3


In [17]:
c = torch.FloatTensor([[2,2,1],[1,1,1],[3,4,5]])


In [18]:
d = torch.DoubleTensor([[2,2,1],[1,1,1],[3,4,5]])


In [21]:
print(c)
print(c.type())

tensor([[2., 2., 1.],
        [1., 1., 1.],
        [3., 4., 5.]])
torch.FloatTensor


In [23]:
print(c.mean())

tensor(2.2222)


In [24]:
print(c.std())

tensor(1.4814)


In [34]:
#print(b.view(-1,1)) # the negative is any number of rows you want
#print(b.view(9)) #flatens it (the number should be size of the array)
# print(b.view(-1,3))
# print(b.view(3,3))# explicitly specifying the nums
b = b.view(1,-1)
print(b)

tensor([[2, 2, 1, 1, 1, 1, 3, 4, 5]])


In [36]:
#create a 3d tensor with 2 chanels,3 rows , 4 columns
three_dim = torch.randn(2,3,4) #n stands for normal distribution
print(three_dim)

tensor([[[ 1.1292,  1.1507,  0.0954,  0.2882],
         [ 1.0574,  2.3110, -0.0830, -0.6775],
         [-0.7581,  0.1685, -1.1915, -0.7570]],

        [[-0.4611, -0.1766, -1.4222, -0.7052],
         [-0.0591,  0.3070,  0.2552,  0.4945],
         [ 0.1424, -1.2526, -1.5347,  0.2251]]])


In [39]:
r = torch.rand(4,4) #without the n it will print between 0 and 1
print(r)

tensor([[0.1616, 0.6891, 0.3616, 0.7185],
        [0.5357, 0.3119, 0.8853, 0.6827],
        [0.1395, 0.4487, 0.6077, 0.2294],
        [0.8523, 0.4538, 0.7377, 0.9409]])


In [45]:
#creating an array of 5 randomn ints excluding 10
in_array = torch.randint(6,10, (3,3)) #the rand int doesnt include the last digit. 
#and the tuple is for showing the shape
print(in_array)

tensor([[6, 7, 9],
        [6, 8, 9],
        [7, 8, 6]])


In [47]:
print(torch.numel(in_array)) #number of elements in the array

9


In [48]:
z = torch.zeros(3,3)
y = torch.ones(3,3)
print(z)
print(y)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [52]:
c_like = torch.randn_like(c, dtype = torch.double)
print(c_like)

tensor([[-0.2185, -1.0103, -0.6033],
        [ 1.3278,  0.4724,  0.1164],
        [ 0.0554,  0.1673, -0.3166]], dtype=torch.float64)


In [54]:
#add two matrices, they have to be of the same shape and data type
add_result = torch.add(z,y)
print(add_result)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [55]:
#inplace addition
z.add_(y)
print(z)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [60]:
#array slicing using C_like
print(c_like[:,1] )
print( c_like[:,:2])# excluding the 2nd column
print(c_like[:3,] )

tensor([-1.0103,  0.4724,  0.1673], dtype=torch.float64)
tensor([[-0.2185, -1.0103],
        [ 1.3278,  0.4724],
        [ 0.0554,  0.1673]], dtype=torch.float64)
tensor([[-0.2185, -1.0103, -0.6033],
        [ 1.3278,  0.4724,  0.1164],
        [ 0.0554,  0.1673, -0.3166]], dtype=torch.float64)


In [65]:
print(c_like)
num = c_like[2,0]
print(num)
print(num.item())

tensor([[-0.2185, -1.0103, -0.6033],
        [ 1.3278,  0.4724,  0.1164],
        [ 0.0554,  0.1673, -0.3166]], dtype=torch.float64)
tensor(0.0554, dtype=torch.float64)
0.05541327178811771
